#pragma once

#include <pebble.h>

#define BG_COLOR GColorWhite

#ifdef PBL_ROUND
#define ACTION_BAR_WIDTH_WITH_GAP (ACTION_BAR_WIDTH + 12)
#else
#define ACTION_BAR_WIDTH_WITH_GAP (ACTION_BAR_WIDTH + 2)
#endif

#define BPM_DEFAULT_BPM_T 1200

#define BPM_FONT FONT_KEY_BITHAM_42_BOLD
#define BPM_FONT_HEIGHT 42

#define BPM_TEXT_INVALID "---"
#define BPM_TEXT_BUFFER_SIZE 10

#define BPM_HINT_FONT FONT_KEY_GOTHIC_24_BOLD
#define BPM_HINT_FONT_HEIGHT 24
#define BPM_HINT_TEXT "Current BPM:"

#ifdef PBL_ROUND
#define METRONOME_HINT_FONT FONT_KEY_GOTHIC_18_BOLD
#define METRONOME_HINT_FONT_HEIGHT 18
#else
#define METRONOME_HINT_FONT FONT_KEY_GOTHIC_14_BOLD
#define METRONOME_HINT_FONT_HEIGHT 14
#endif
#define METRONOME_HINT_TEXT "Metronome BPM:"

#define METRONOME_VIBE_DURATION_MS 50

#define METRONOME_EDIT_TAP_REPEAT_MS 30

#define TAP_TIMEOUT_SECONDS 2
